LectureString_tests.exe: LectureString.cpp LectureString_tests.cpp
	g++ -g -Wall -Werror -pedantic -std=c++11 -g LectureString.cpp LectureString_tests.cpp -o LectureString_tests.exe

Filter_tests.exe: Filter.cpp Filter_tests.cpp
	g++ -g -Wall -Werror -pedantic -std=c++11 -g Filter.cpp LectureString.cpp Filter_tests.cpp -o Filter_tests.exe
