sorted_array_puzzles_test.exe: sorted_array_puzzles_test.cpp sorted_array_puzzles.cpp
	g++ -g -Wall -Werror -pedantic -std=c++11 -g sorted_array_puzzles_test.cpp sorted_array_puzzles.cpp -o sorted_array_puzzles_test.exe
